### ISSUE TITLE
wrong build dates for provided images (47 years ago)

### ISSUE THREAD

**Issue by Kosta-Github** [GoogleCloudPlatform/distroless#112]
when pulling the current images, the build date says `47 years ago`, e.g.:
```
$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
gcr.io/distroless/nodejs   latest              3a4657735d4c        47 years ago        73.7MB
gcr.io/distroless/base     latest              60e504d8f1de        47 years ago        15.7MB

$ docker -v
Docker version 17.09.0-ce, build afdb6d4
```

**Comment by mattmoor** [comment]
We do this to get verifiable / reproducible builds.  We are going to change this to use `SOURCE_DATE_EPOCH` to reflect the time of the source commit once Bazel adds support for that, but for now we use the Unix epoch.

[Here's](https://github.com/bazelbuild/rules_docker/issues/155) the tracking issue on the Bazel/Docker side.
