### ISSUE TITLE
Upgrading node to 8 LTS

### ISSUE THREAD

**Issue by ajuhaszcf** [GoogleCloudPlatform/distroless#126]
Would it be possible to upgrade the nodejs image to run v8 of node?

**Comment by r2d4** [comment]
Sure.  It should be as easy as updating this entry
https://github.com/GoogleCloudPlatform/distroless/blob/master/WORKSPACE#L90-L97

PRs are of course welcome, but if not, we'll upgrade it soon.

**Comment by ajuhaszcf** [comment]
PR #127 :)
Thanks for the help!

One more question... The build worked and I can see the results in `bazel-bin/nodejs/nodejs-layer` how do I make that into a docker image?
