### ISSUE TITLE
Building images requires installing `gcloud`

### ISSUE THREAD

**Issue by hwright** [GoogleCloudPlatform/distroless#131]
On a fresh clone of the git repository, on a clean vm of one's choice, building a distroless image requires first installing the `gcloud` commandline tool.  It seems that `print-workspace-status.sh` is using `gcloud` for something:
```
$ bazel build python2.7:python27
INFO: Found 1 target...
ERROR: Process exited with status 127: Process exited with status 127.
./print-workspace-status.sh: line 8: gcloud: command not found
Target //python2.7:python27 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 107.303s, Critical Path: 0.05s
$
```

This would appear to be an extraneous dependency.  We should consider removing it.

**Comment by r2d4** [comment]
This sounds good to me.  It's used to get the current project_id, which is only used for the publish step.
