### ISSUE TITLE
Create gcr.io/distroless/dotnet base image

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/distroless#141]
Suggest creating the actual image of dotnet distroless on gcr.io:   ```gcr.io/distroless/dotnet```

The current set of images does not include it: 

- https://github.com/GoogleCloudPlatform/distroless#docker

(otherwise, i had to gen it by hand, eg (on [google cloud shell](https://cloud.google.com/shell/docs/quickstart) with docker 17, dotnet 2 built in):

```bash
git clone https://github.com/GoogleCloudPlatform/distroless.git
cd distroless/
bazel build dotnet:dotnet
bazel run dotnet:dotnet
```

(i tagged and pushed to my repo)
```bash
docker tag bazel/dotnet:dotnet salrashid123/bazeldotnet
docker push salrashid123/bazeldotnet
```

```bash
mkdir console
cd console/
dotnet new console
```

Dockerfile
```dockerfile
FROM microsoft/dotnet:2.0.0-sdk AS build-env
ADD . /app
WORKDIR /app
RUN dotnet restore
RUN dotnet publish  -c Release

FROM docker.io/salrashid123/bazeldotnet
WORKDIR /app
COPY --from=build-env /app /app/
ENTRYPOINT ["dotnet", "bin/Release/netcoreapp2.0/console.dll"]
```

then
```
docker build -t myapp .
docker run -t myapp
```

**Comment by mattmoor** [comment]
If you open in a browser: [gcr.io/distroless/dotnet](https://gcr.io/distroless/dotnet) you see we're publishing it.  Do you want to send a PR to update the docs?

**Comment by salrashid123** [comment]
shoot...shoud've tried the url!

here's the PR #142

**Comment by salrashid123** [comment]
PR is merged so i'll close this out; I'll open up a new issue to add docker-based multi-stage examples (vs bazel0
