### ISSUE TITLE
Travis test faiure with pylint

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/distroless#158]
************* Module package_manager.dpkg_parser
W:106,20: Exception arguments suggest string formatting might be intended (raising-format-tuple)
W:111,20: Exception arguments suggest string formatting might be intended (raising-format-tuple)

See https://travis-ci.org/GoogleCloudPlatform/distroless/builds/329495150?utm_source=github_status&utm_medium=notification for the full log and https://github.com/GoogleCloudPlatform/distroless/pull/157 for the PR.

**Comment by r2d4** [comment]
Fixed in #161
