### ISSUE TITLE
Missing the latest

### ISSUE THREAD

**Issue by larsskj** [GoogleCloudPlatform/distroless#52]
Hi Matthew,

I attended you session at SwampUp and wanted to try distroless: As Python is the thing for me, I started with Python27. Unfortunately, Docker refuses to pull it - it claims there's no image tagged latest.

The base image and the Java image works fine.

Regards,
Lars

**Comment by mattmoor** [comment]
The image name is: `gcr.io/distroless/python2.7`

If you put it in your browser, it should pull up the GCR UI (and I see `latest`).  Maybe a `.` was missing from my slide?

**Comment by larsskj** [comment]
Right you are - I'm sure I copy/pasted the python27 from somewhere - but adding the dot, it works!

Thanks for a very fine initiative, I look forward to play around.
