### ISSUE TITLE
swamup talk link does not contain more information

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/distroless#54]
I followed the 
'For more information, see this talk.'
but I did not notice any new information or link to presentations or video at the destination:
https://swampup2017.sched.com/event/A6CW/distroless-docker-containerizing-apps-not-vms

**Comment by mattmoor** [comment]
@patflynn I'm not sure the video is online yet.

**Comment by patflynn** [comment]
Aha. I'm just noticing the date on it.
