### ISSUE TITLE
Problems creating docker entrypoint with '--' as last argument

### ISSUE THREAD

**Issue by gebi** [GoogleCloudPlatform/distroless#56]
Hi,

I'd really like to create a few base containers which can be used in production, but i couldn't get entrypoint of the docker_build rule in bazel to work properly.

Every time i need a closing '--' in an docker entrypoint bazel removes it and outputs an empty array, generating invalid docker metadata which docker refuses to load.

Is there a workarround i simply do not know in bazel to get this to work?

Generated metadata:
```
% cat bazel-bin/init/init-base.config
{"architecture": "amd64", "author": "Bazel", "config": {"Entrypoint": ["/tini", []], "User": "user"},
                                                                                ^^^
```

bazel log output
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ init/init-base
Skipping 2115094ee05658502a4cc9c28712baf34771c16b3de76f4a33499b463b8d7db5, already loaded.
Skipping 59fcdb78566467803b3ace1801501ca8b6754e55abe23d737be5a4245c1f21ea, already loaded.
Loading d58de6f97f4bb229e55abb7d6a13fbaf19590dc39b8939b66ede14fb6cd2e841...
json: cannot unmarshal array into Go value of type string
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
```

Bazel BUILD file example
```bzl
docker_build(
    name = "init-base",
    base = "//base:base",
    entrypoint = ["/tini", "--"],
    tars = [
        ":tini.tar",
        ":init_passwd.passwd.tar",
    ],
    user = "user",
)
```

Link to my experiment (my redis branch contains both the init and redis container)
https://github.com/mgit-at/distroless/blob/redis/init/BUILD#L28

**Comment by mattmoor** [comment]
This looks like a docker_build bug, so I'm going to open a new issue on the right repo to track it.

**Comment by mattmoor** [comment]
Seems like a bug in `argparse` since `--entrypoint=--` is coming through as a `[]` entry in our list...

**Comment by duggelz** [comment]
A bug in argparse for sure.  A workaround is possible by postprocessing arg.entrypoint just after parsing, replacing all [] with '--'.  It seems to be only '--' that is affected, '-' or '---', or '--anything' works fine.

Note that --entrypoint= (empty string) is distinguishable from --entrypoint=[], so you don't have to worry about that:

    python ./foo.py --entrypoint=-- --entrypoint=foo --entrypoint=''
    [[], 'foo', '']

**Comment by duggelz** [comment]
Here's the argparse bug: https://bugs.python.org/issue14364

**Comment by mattmoor** [comment]
Thanks @duggelz I will add some logic to do this.

**Comment by mattmoor** [comment]
Just to close things here, the linked issue is closed now.  LMK if you have any problems.
