### ISSUE TITLE
dpkg rules: Not all package names are valid bazel rule names

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/distroless#70]
In the dpkg rules, the bazel rule name is also the name of the package to be downloaded.  Not all package names are valid bazel rule names, e.g.  
```
http_file(
    name = "libstdcpp6",
    sha256 = "f1509bbabd78e89c861de16931aec5988e1215649688fd4f8dfe1af875a7fbef",
    url = "http://deb.debian.org/debian/pool/main/g/gcc-4.9/libstdc++6_4.9.2-10_amd64.deb",
)
```
Ideally, I'd like to avoid
```
dpkg(
    name = "libstdc"
    package_name = "libstdc++"
    source = "@debian_jessie//file:Packages.json",
)
```

**Comment by mattmoor** [comment]
I'd rather support an optional `name` kwarg that defaults to `package_name` than drop the user on the floor.

We can also surface a better error message for this ourselves...
