### ISSUE TITLE
base: wrong permissions of /tmp 

### ISSUE THREAD

**Issue by f0** [GoogleCloudPlatform/distroless#75]
/tmp should have the permissions 01777
the created tmp diretory has 755

so ony root can write to tmp, any app running with other permissions fails 

```
sudo docker run -ti bazel/busybox:debug 
/ # ls -l /
total 24
drwxr-xr-x    2 1000     1000          4096 Jan  1  1970 busybox
drwxr-xr-x    5 root     0              360 Jul 20 14:57 dev
drwxr-xr-x    1 root     0             4096 Jul 20 14:57 etc
drwxr-xr-x    1 root     0             4096 Jan  1  1970 lib
drwxr-xr-x    2 root     0             4096 Jan  1  1970 lib64
dr-xr-xr-x  238 root     0                0 Jul 20 14:57 proc
dr-xr-xr-x   13 root     0                0 Jul 19 12:38 sys
drwxr-xr-x    2 root     0             4096 Jan  1  1970 tmp
drwxr-xr-x    1 root     0             4096 Jan  1  1970 usr
```

**Comment by mattmoor** [comment]
@dlorenc We should see if checking in a tarball with `/tmp` @ the appropriate mode works via `tars=[...]`, and if it does replace the `empty` trick.

**Comment by f0** [comment]
@mattmoor  i generated a tmp.tar with the correct permissions (manually) , now it looks good
```
tar tvf bazel-bin/base/base-layer.tar | grep tmp
drwxrwxrwt 1000/1000         0 1970-01-01 01:00 ./tmp/
```
but , i cannot create this with e.g genfile, i always got the error tar /tmp already exists (or permission denied with chmod).

**Comment by mattmoor** [comment]
@f0 Would you be willing to send a PR to replace [this](https://github.com/GoogleCloudPlatform/distroless/blob/master/base/BUILD#L22)?

**Comment by f0** [comment]
@mattmoor  sure
