### ISSUE TITLE
Support .NET distroless 

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/distroless#83]
FR to support coreCLR distroless builds once we actually support [coreCLR in bazel](https://github.com/bazelbuild/rules_dotnet/issues/39)

FWIW, here's a [sample coreCLR distroless build](https://github.com/salrashid123/dotnet_distroless)  where the coreCLR binary is generated outside of bazel

**Comment by mattmoor** [comment]
We don't support Node in Bazel, and yet we have a distroless image.  Up for a PR?

**Comment by salrashid123** [comment]
I don't mind submitting the PR.  Do you think there is use in a distroless build where the actual binary is build outside of bazel?  I can see where bazel is just the mechanism used here for distroless builds so there isn't technically a dependency or requirement we have .NET in bazel first before .net w/ distroless.   If that sounds good, i'll fine sometime to submit the PR.

**Comment by colemickens** [comment]
Personally, I think so. I could convert all of my build to Bazel except some bash to drive the .NET Core 2 build until the dotnet rules evolve .NET Core 2 support.

**Comment by salrashid123** [comment]
ok, fwiw, submitted [PR #88](https://github.com/GoogleCloudPlatform/distroless/pull/88).  PTAL and try it out...its a basic build though.

(from fork/branch [here](https://github.com/salrashid123/distroless/tree/dotnet-distroless)

**Comment by salrashid123** [comment]
PR88 merged
