### ISSUE TITLE
package_manager support for specific versions of packages

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleCloudPlatform/distroless#92]
In using the distroless/package_manager, I can't seem to find a way to pull specific versions of a package.  Is there a method currently to pull specific versions of a package?  Thanks.

**Comment by r2d4** [comment]
Currently, we're fetching snapshots of a package list in a point in time.  You can search for specific packages across all snapshots with http://snapshot.debian.org/, but I don't they expose an API to pull packages by version programmatically.  

Without much refactoring, we could probably add a `version` attribute to the `dpkg` rule to pull the specific version across all the source lists that you've provided, although you'd still have to find and provide the appropriate snapshots.

**Comment by MarkusTeufelberger** [comment]
I am currently working on a fork of distroless that would allow you to specify several different sources of deb files including support for handling repositories with more than one version of the same package. Not ready for a PR yet though and still needs some refinement. Once it is done, I'll see if there is some interest in upstreaming it.

**Comment by dlorenc** [comment]
Fixed with #99
