### ISSUE TITLE
request to have debian package tzdata in distroless/base

### ISSUE THREAD

**Issue by cybrcodr** [GoogleCloudPlatform/distroless#95]
Not sure if other language runtimes use this, but the Go time package does.  It would be nice if at least the directory /usr/share/zoneinfo and files under it are packaged into distroless/base.

**Comment by mattmoor** [comment]
@r2d4 you want to TAL at how big this is?  I've seen folks wanting this in the mono-repo too.

**Comment by cybrcodr** [comment]
Just fyi regarding our usage.  We have a Go builder images (gcr.io/gcp-runtimes/go1-builder) that generate Dockerfile with distroless/base as the base image.  See https://github.com/GoogleCloudPlatform/golang-docker/blob/master/runtime-builder/go-build.sh#L50.  We currently have to copy this in.

Thanks for considering.
